import './globals.css'
import type { Metadata } from 'next'
import { DM_Sans, Inter } from "next/font/google";

const dmSans = DM_Sans({ weight: ["400", "500", "700"] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dmSans.className}>{children}</body>
    </html>
  )
}
